cloud: education-us-west-2
region: us-west-2
head_node_type:
  name: head_node_type
  instance_type: g5.4xlarge
worker_node_types:
- name: gpu_worker
  instance_type: g5.4xlarge
  min_workers: 1
  max_workers: 1
  use_spot: False
aws:
  BlockDeviceMappings:
  - DeviceName: "/dev/sda1"
    Ebs:
      VolumeSize: 500
      DeleteOnTermination: true
  TagSpecifications:
  - ResourceType: instance
    Tags:
      - Key: as-feature-multi-zone
        Value: "true"
