name: madewithml
project_id: prj_wn6el5cu9dqwktk6t4cv54x8zh
cluster_env: madewithml-cluster-env
compute_config: madewithml-cluster-compute
ray_serve_config:
  import_path: deploy.services.serve_model:entrypoint
  runtime_env:
    working_dir: .
    upload_path: s3://madewithml/kehsihba/services  # <--- CHANGE USERNAME (case-sensitive)
    env_vars:
      GITHUB_USERNAME: abhishek-1131  # <--- CHANGE USERNAME (case-sensitive)
rollout_strategy: ROLLOUT # ROLLOUT or IN_PLACE
